function generate() {
  const lista = {
    1: "Leonardo Dicaprio",
    2: "Matt Damon",
    3: "Dane DeHaan",
    4: "Keanu Reeves",
    5: "Jacob Elordi",
    6: "Tom Blyth",
    7: "Chad Michael Murray",
    8: "Robert Pattinson",
    9: "Heather Ledger",
    10: "Hayden Christensen",
    11: "Andrew Garfield",
    12: "Louis Partridge",
    13: "Benjamin Wadsworth",
    14: "Timothee Chalamet",
    15: "Tom Felton",
    16: "Tom Hudges",
    17: "Ian Somerhalder",
    18: "Lorenzo Zurzolo",
    19: "Evan Peters",
    20: "Theo James",
    21: "Dylan O’Brien",
    22: "Sam Claflin",
    23: "Kurtis Conner",
    24: "Danny Gonzalez",
    25: "Drew Gooden",
    26: "Josh Hutcherson",
    27: "Cillian Murphy",
    28: "Pedro Pascal",
    29: "Ryan Gosling",
    30: "Henry Cavill",
    31: "Michael Mrazik",
    32: "Robert Downey jr",
    33: "Ben Barnes",
    34: "Tom Hiddleston",
    35: "Tom Holland",
    36: "Chris Evans",
    37: "Aaron Taylor Johnson",
    38: "Joe Alwyn",
    39: "Christian Bale",
    40: "Louis Garrel",
    41: "Benedict Cumberbatch",
    42: "Adrien Brody",
    43: "Freddy Carter",
    44: "Hozier",
    45: "V (BTS)",
    46: "Jimin (BTS)",
    47: "Jungkook (BTS)",
    48: "RP (BTS)",
    49: "Suga (BTS)",
    50: "J-Hope (BTS)",
    51: "Jaehyun (NCT)",
    52: "Yuta (NCT)",
    53: "Taeil (NCT)",
    54: "WINWIN (NCT)",
    55: "Johnny (NCT)",
    56: "Mark Lee (NCT)",
    57: "Park Ji-Sung (NCT)",
    58: "Jeno (NCT)",
    59: "Sunghoon (Enhypen)",
    60: "Sunoo (Enhypen)",
    61: "Jay (Enhypen)",
    62: "Niki (Enhypen)",
    63: "Sehun (EXO)",
    64: "Chanyeol (EXO)",
    65: "Felix (Stray Kids)",
    66: "Kai (EXO)",
    67: "Hyunjin (Stray Kids)",
    68: "Mingi (Ateez)",
    69: "Seonghwa (Ateez)",
    70: "Hongjoong (Ateez)",
    71: "Yunho (Ateez)",
    72: "Yeosang (Ateez)",
    73: "Wooyoung (Ateez)",
    74: "Jongho (Ateez)",
    75: "San (Ateez)",
    76: "Jinyougn (CIX)",
    77: "Seunghun (CIX)",
    78: "IM (Monsta X)",
    79: "Wonho (Monsta X)",
    80: "JooHoney (Monsta X)",
    81: "Hyungwo (Monsta X)",
    82: "T:O:P (Big Bang)",
    83: "G-Dragon (Big Bang)",
    84: "Baekhyun (EXO)",
    85: "The8 (Seventeen)",
    86: "Hoshi (Seventeen)",
    87: "DK (Seventeen)",
    88: "Joshua (Seventeen)",
    89: "Zuho (SF9)",
    90: "Jaeyoon (SF9)",
    91: "Rowoon (SF9)",
    92: "Taeyang (SF9)",
    93: "Tom Hanks",
    94: "Brad Pitt",
    95: "Robin Williams",
    96: "Taemin",
    97: "David Tennant",
    98: "Tom Cruise",
    99: "Anthony Hopkins",
    100: "Al Pacino",
    101: "Jim Carrey",
    102: "Nicolas Cage",
    103: "Robert De Niro",
    104: "Harrison Ford",
    105: "Arnold SchSchwarzenegger",
    106: "Pierce Brosnan",
    107: "Adam Sandler",
    108: "George Clooney",
    109: "Kevin Costner",
    110: "Johnny Depp",
    111: "Jude Law",
    112: "Gary Oldman",
    113: "Tobey Maguire",
    114: "Hugh Grant",
    115: "Ethan Hawke",
    116: "Alan Rickman",
    117: "Jared Leto",
    118: "Wes Bentley",
    119: "Elijah Wood",
    120: "Jeremy Irons",
    121: "Ben Wishaw",
    122: "Christopher Eccleston",
    123: "Matt Smith",
    124: "Peter Capaldi",
    125: "Nciuti Gatwa",
    126: "Oscar Isaac",
    127: "Mads Mikkelsen",
    128: "Michael Sheen",
    129: "Taika Waititi",
    130: "Jensen AceAcek",
    131: "Jackie Chan",
    132: "Hugh Jackman",
    133: "Josh Holloway",
    134: "Matthew Fox",
    135: "Naveen Andrews",
    136: "Daniel Dae Kim",
    137: "Dominic Monaghan",
    138: "Terry O'Quinn",
    139: "Henry Ian Cusick",
    140: "Noah Schnapp",
    141: "Finn Wolfhard",
    142: "Caleb McLaughlin",
    143: "Gaten Matarzzo",
    144: "Joe Keery",
    145: "Charlie Heaton",
    146: "Dacre Montgomery",
    147: "Joseph Quinn",
    148: "Liam Hemsworth",
    149: "Chris Hemsworth",
    150: "Lenny Kravitz",
    151: "Donald Sutherland",
    152: "Woody Harrelson",
    153: "Will Poulter",
    154: "Ki Hong Lee",
    155: "Thomas Brodie-Sangster",
    156: "Robert Sean Leonard",
    157: "Gale Hansen",
    158: "Josh Charles",
    159: "Bojan (Joker Out)",
    160: "Nace (Joker Out)",
    161: "Jan (Joker Out)",
    162: "Kris (Joker Out)",
    163: "Jure (Joker Out)",
    164: "Jack Wolfe",
    165: "Andrew Rannells",
    166: "Christian Borle",
    167: "Daveed Diggs",
    168: "Leslie Odom Jr",
    169: "Anthony Ramos",
    170: "Lin Manuel Miranda",
    171: "Józef Stalin",
    172: "Joaquin Phoenix",
    173: "Joseph Gordon-Levitt",
    174: "Maciej Musiał",
    175: "Kit Young",
    176: "Callahan Skogman",
    177: "Patrick Gibson",
    178: "Wendigoon",
    179: "Mike’s Mic",
    180: "Markiplier",
    181: "Johnnie Guilbert",
    182: "Dylan is in trouble",
    183: "Christian Slater",
    184: "Andrew Scott",
    185: "Michał Żebrowski",
    186: "Aleksandr Domogarow",
    187: "Jan Ravnik",
    188: "Raphael Thomas",
    189: "Dallon Weekes",
    190: "Michael Cera",
    191: "Gerard Way",
    192: "Avan Jogia",
    193: "Jake Webber",
    194: "Josh Andress Rivera",
    195: "Jerzy Kamas",
    196: "Nicholas Galitzine",
    197: "Taylor Zakhar Perez",
    198: "Albert Camus",
    199: "Ross Lynch",
    200: "Shawn Mendes",
    201: "Troye Sivan",
    202: "Artur Żmijewski",
    203: "Harry Styles",
    204: "Niall Horan",
    205: "Edvin Ryding",
    206: "Omar Rudberg"
  };

  let random1 = Math.floor(Math.random() * (206 - 1) + 1);
  let random2 = Math.floor(Math.random() * (206 - 1) + 1);

  while(random1 == random2){
    random2 = Math.floor(Math.random() * (206 - 1) + 1);
  }
  console.log("random1 = ", random1)
  console.log(lista[`${random1}`])
  console.log("random2 = ", random2)
  console.log(lista[`${random2}`])

  const zdj1 = document.querySelector("#img");
  const zdj2 = document.querySelector("#imgg");

  const podpis1 = document.querySelector("#podpisik");
  const podpis2 = document.querySelector("#podpisikk");

  zdj1.setAttribute("src", `img/zdjecia_ziomow/${random1}.jpg`);
  zdj2.setAttribute("src", `img/zdjecia_ziomow/${random2}.jpg`);

  podpis1.innerText = lista[`${random1}`]
  podpis2.innerText = lista[`${random2}`]
}
